### ISSUE TITLE
关于paper的问题

### ISSUE THREAD

**Issue by bucktoothsir** [llcshappy/Monocular-3D-Human-Pose#10]
hi 你好 最近看了你这篇paper， idea非常棒。但是有2个地方有点困惑。1. 在paper中提到最后恢复3d的geometric search scheme是需要相机内参的，但是对于in the wild的图像是没有这个信息的，那么这个时候怎么处理？2. 同样在geometric search scheme的步骤中需要用到2d-pose的gt，请问这个2d-pose就是网络输入的left-view的2d pose吗？

**Comment by llcshappy** [comment]
你好，不好意思剛剛看到留言。第一個問題，我們有一個假設，就是所有的圖像我們都認爲是採用的h36m相機的內參。第二個問題，用到的gt爲網絡的輸入，即左視圖的2D pose。

**Comment by lvandoit** [comment]
hi:
sorry for bother. I have a puzzler about the paper. I noticed that the lsp and mpii dataset been used in the training step. However the joints' annotation of Human 3.6m dataset is different from them. So how can you use all of them together? (human 3.6m has 16 joints used with Thorax、Spine、Hip、foot, but lsp has 14 joints without these joints . Thanks for your time and any reply. @bucktoothsir @llcshappy
