### ISSUE TITLE
Could not find the train scripts (*.sh)

### ISSUE THREAD

**Issue by huge123** [llcshappy/Monocular-3D-Human-Pose#6]
Thanks for sharing the codes. But it seems that the some files described in README.md like 3Dpose.sh have not been uploaded, I wonder when these files would be opened? 
By the way, the pre-trained model can not been accessed to yet.

looking forward to your reply.

**Comment by llcshappy** [comment]
I will upload the pre-trained model. Actually, all the codes of the 3D label generator have been released. I will update the readme for you. Thanks for your attention!
