### ISSUE TITLE
some issue about the code

### ISSUE THREAD

**Issue by lvandoit** [llcshappy/Monocular-3D-Human-Pose#8]
hi:
    his code seems to be incomplete. Can you upload the complete code @llcshappy

**Comment by llcshappy** [comment]
Actually, we have already uploaded all the complete code. Can you tell us which problem you encountered in the algorithm? so we can help you solve the problem.

**Comment by lvandoit** [comment]
hi:
  Thanks for you reply and your work.Do you have the human 3.6m dataset?I am a student in Shanghai Institute of Advanced Studies Chinese Academy of Science . i am reseaching the work about 3d human pose estimation,so i need the dataset to training my network, Cloud you give me some guidance,thanks@llcshappy

**Comment by lvandoit** [comment]
hi:
Thanks for you reply and your work.Do you have the human 3.6m dataset?I am a student in Shanghai Institute of Advanced Studies Chinese Academy of Science . i am reseaching the work about 3d human pose estimation,so i need the dataset to training my network, Cloud you give me some guidance,thanks @llcshappy

**Comment by llcshappy** [comment]
OK. We can contact by e-mail. (wangluyang@sensetime.com)

**Comment by amrbenattia** [comment]
@llcshappy the code is incomplete. 
can you tell where is demo.py or gen_right.py?

**Comment by lvandoit** [comment]
hi:
sorry for bother. I have a puzzler about the paper. I noticed that the lsp and mpii dataset been used in the training step. However the joints' annotation of Human 3.6m dataset is different from them. So how can use all of them together? (human 3.6m has 16 joints used with Thorax、Spine、Hip、foot, but lsp has 14 joints without these joints . Thanks for your time and any reply. @amrbenattia
